import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "./_components/topnav";
import { MyStoreProvider } from "~/lib/store/provider";

export const metadata = {
  title: "Cool Stuff",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <MyStoreProvider>
        <html lang="en" className={`${GeistSans.variable} `}>
          <body className="dark">
            {/* <TopNav /> */}
            {children}
          </body>
        </html>
      </MyStoreProvider>
    </ClerkProvider>
  );
}
